---
version: 2
models:
- name: "mod"
  columns:
  - name: "A"
    tests:
    - unique:
        config:
          fail_calc: "count(1)"
          warn_if: " >= 0 "
          where: "B != 100"
          severity: "warn"
          store_failures: true
          error_if: " > 100 "
    dataType:
      type: "Integer"
  - name: "B"
    dataType:
      type: "Integer"
  tests: []
