---
version: 2
models:
- name: "mod"
  columns:
  - name: "A"
    tests:
    - unique:
        config:
          fail_calc: "count(*)"
          error_if: " > 100 "
          warn_if: " > -1 "
          where: "B != 10"
          store_failures: true
          severity: "error"
    dataType:
      type: "Integer"
  - name: "B"
    dataType:
      type: "Integer"
  tests: []
